pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Clone the repo
                git 'https://github.com/Jayakumar8055/Jenkins-Practices'
            }
        }
        
        stage('Compile') {
            steps {
                script {
                   sh 'cd first-pipeline && javac helloWorld.java'
                }
            }
        }

        stage('Run') {
            steps {
                script {
                    sh 'cd first-pipeline && java helloWorld'
                }
            }
        }
    }
}
