pipeline {
    agent any

    stages {
        stage('Compile') {
            steps {
                script {
                   sh 'cd first-pipeline && javac helloWorld.java'
                }
            }
        }

        stage('Run') {
            steps {
                script {
                    sh 'cd first-pipeline && java helloWorld'
                }
            }
        }
    }
}
